[project]
name = "pc"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.3.3",
    "psutil>=7.1.0",
    "typed-argument-parser>=1.11.0",
    "uiautomator2>=3.4.2",
]
